name: "Vuln Docker Scanners Wapiti Action"
description: "Runs wapiti on a target host"
author: gipo355
inputs:
  github_token:
    description: "GitHub token"
    required: true
  target:
    description: "Host to scan"
    required: true
    default: "localhost"
runs:
  using: "node20"
  main: "dist/index.js"
  # post: "dist/index.js"
